name: Deploy Angular to FTP Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.10.0

      - name: Install dependencies
        run: npm install

      - name: Update API URL for production
        run: |
          # Define the file path
          FILE_PATH="src/app/services/api.service.ts"

          # Ensure the file exists
          if [ ! -f "$FILE_PATH" ]; then
            echo "Error: $FILE_PATH not found!" && exit 1
          fi

          # Update baseURL to production API
          sed -i "s|baseURL: 'http://new-turki-project-api-v2.test/api/v2'|baseURL: 'https://almaraacompany.com/dashboard/api/v2'|" $FILE_PATH

          # Confirm the update
          echo "Updated $FILE_PATH:"
          cat $FILE_PATH

      - name: Build Angular App
        run: npm run build -- --configuration=production

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: almaraacompany.com
          username: ${{ secrets.server_master_turki_name }}
          password: ${{ secrets.server_master_turki_password }}
          local-dir: ./dist/maraa_web/ # Source directory on the server
          server-dir: /public_html/dashboard-v4/ # Target directory on the server
          protocol: ftps
          port: 21

      - name: Clear caches
        run: |
          # Clear the npm cache
          npm cache clean --force
          # If you want to clear Angular CLI cache (Angular 13+)
          npx ng cache clean --force
